---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r}
raw_activity <- read.csv("activity.csv",header=TRUE)
activity <- raw_activity[complete.cases(raw_activity),]
```


## What is mean total number of steps taken per day?
```{r}
daily_total <- aggregate(x=activity$steps, by=list(date=activity$date), FUN="sum")
summary(daily_total)
daily_total$date <- strptime(daily_total$date,"%Y-%m-%d ")
plot(daily_total$date, daily_total$x,type="h",main="Total steps by date", xlab="Date",ylab="Total Steps")
cat("Mean: ",mean(daily_total$x))
cat("Median: ",median(daily_total$x))
```

## What is the average daily activity pattern?
```{r}
daily_avg <- aggregate(x=activity$steps, by=list(interval=activity$interval), FUN="sum")
plot(daily_avg$interval, daily_avg$x,type="l",main="Average steps by 5 minutes interval", xlab="Interval",ylab="Avg Steps")
cat("Maximum number of step ",daily_avg[order(-daily_avg$x),][1,2])
cat("at interval ",daily_avg[order(-daily_avg$x),][1,1])
```

## Imputing missing values
```{r}
for(i in 1:nrow(daily_avg)){
row <- daily_avg[i,]
interval <- row$interval
steps <- row$x/24
raw_activity[raw_activity$interval==interval & is.na(raw_activity$steps),1] <- steps
}

new_daily_total <- aggregate(x=raw_activity$steps, by=list(date=raw_activity$date), FUN="sum")
new_daily_total$date <- strptime(new_daily_total$date,"%Y-%m-%d ")
plot(new_daily_total$date, new_daily_total$x,type="h",main="Total steps by date with Imputing values", xlab="Date",ylab="Total Steps")


```

## Are there differences in activity patterns between weekdays and weekends?
```{r}
week_activity <- raw_activity
week_activity$date <- strptime(week_activity$date,"%Y-%m-%d ")
week_activity$day <- ""
for(i in 1:nrow(week_activity)) {
  row <- week_activity[i,]  
  week_activity[i,]$day <- if(substring(weekdays(row$date),1,1)=="S") "Weekend" else  "Weekday"
}

weekday_activity <- week_activity[week_activity$day=="Weekday",]
weekday_avg <- aggregate(x=weekday_activity$steps, by=list(interval=weekday_activity$interval), FUN="sum")
plot(weekday_avg$interval, weekday_avg$x,type="l",main="Weekday Average steps by 5 minutes interval", xlab="Interval",ylab="Avg Steps")

weekend_activity <- week_activity[week_activity$day=="Weekend",]
weekend_avg <- aggregate(x=weekend_activity$steps, by=list(interval=weekend_activity$interval), FUN="sum")
plot(weekend_avg$interval, weekend_avg$x,type="l",main="Weekend Average steps by 5 minutes interval", xlab="Interval",ylab="Avg Steps")

```